spring:
  profiles:
    active: 
    - dev


---

server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client-name

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB01
      username: root
      password: root
      dbcp2:
        min-idle: 5             # 数据库连接池最小维持连接数
        initial-size: 5         # 初始化连接数
        max-total: 5            # 最大连接数
        max-wait-millis: 200 

        
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wxp.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml        
        
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservice-dept-8001
    prefer-ip-address: true

info:
  app.name: wxp-springcloud
  company.name: www.e-nci.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client-name

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB03
      username: root
      password: root
      dbcp2:
        min-idle: 5             # 数据库连接池最小维持连接数
        initial-size: 5         # 初始化连接数
        max-total: 5            # 最大连接数
        max-wait-millis: 200 

        
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wxp.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml        
        
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservice-dept-8001
    prefer-ip-address: true

info:
  app.name: wxp-springcloud
  company.name: www.e-nci.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  